name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark-ml:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install python3 dependency
        run: |
              apt-get install --reinstall python3.7
              apt-get install --reinstall python3.7-dev
              apt-get install --reinstall python3.7-tk
              pip3 install virtualenv==16.7.8
      - name: Setting up virtual environment
        run: virtualenv -p python3 ./python/venv  --system-site-packages
      - name: Entering the virtual python environment..
        run: . ./python/venv/bin/activate
      - name: Installing additional requirements for gail 4 bark
        run: pip install -r utils/docker/installers/requirements.txt
      - name: Running unit tests..
        run: bazel test :unit_tests
      - name: Running generate and load tests..
        run: bazel test :generate_load_tests
      - name: Running gail tests..
        run: bazel test :gail_tests
      - name: Running examples..
        run: bazel test :examples_tests
