# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ubuntu-latest CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python
      run: sudo apt-get install python3.7 python3.7-dev python3.7-tk
    - name: Install virtualenv
      run: pip3 install virtualenv==16.7.8
    - name: Create virtual environment
      run: virtualenv -p python3.7 ./python/venv        
    - name: Entering the virtual python environment
      run: . ./python/venv/bin/activate
    - name: Installing requirements
      run: pip3.7 install --no-cache-dir --upgrade --trusted-host pypi.org -r utils/requirements.txt
    - name: Runing bazel tests..
      run: bazel test //...
