# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ubuntu-latest CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python
      run: sudo apt-get install python3.7 python3.7-dev python3.7-tk
    - name: Install virtualenv
      run: pip3 install virtualenv==16.7.8
    - name: Setting up virtual environment
      run: |
        ls
        chmod +x install.sh
        ./install.sh
    - name: Entering the virtual python environment..
      run: source dev_into.sh
    - name: Runing bazel tests..
      run: bazel test //...
